# Generated by Django 4.2.7 on 2024-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link_to_git', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на ресурс')),
                ('hours_to_complete', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('necessary_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
