# Generated by Django 4.2.7 on 2024-09-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hours_to_complete',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link_to_git',
        ),
        migrations.RemoveField(
            model_name='project',
            name='necessary_level',
        ),
        migrations.AddField(
            model_name='project',
            name='hoursToComplete',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Часы на выполнение'),
        ),
        migrations.AddField(
            model_name='project',
            name='necessaryLevel',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Необходимый уровень'),
        ),
        migrations.AddField(
            model_name='project',
            name='taskExperience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт за проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='СompleteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField(verbose_name='Студент')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Слаг')),
                ('leadTime', models.DurationField(blank=True, null=True, verbose_name='Время выполнения')),
                ('gainedExperience', models.IntegerField(verbose_name='Полученный опыт')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Завершенный проект',
                'verbose_name_plural': 'Завершенные проекты',
            },
        ),
    ]
